<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BacklogController extends Controller
{
    public function index()
    {
        // Data dummy sesuai desain Figma — halaman Backlog
        $items = [
            [
                'no_aset'       => 'AST-TGL-001',
                'nama_penyewa'  => 'Drs. Bambang S.',
                'daop'          => 'Daop 4',
                'unit'          => 'Properti',
                'nm'            => 'KA-BD-01',
                'mr'            => 'MR-001',
                'no_kontrak'    => 'KTR-2024-001',
                'tgl_mulai'     => '01-01-2024',
                'tgl_akhir'     => '31-12-2025',
                'nm2'           => 'NM-002',
                'luas'          => '250 m²',
                'harga_satuan'  => 'Rp 1.200.000',
                'nilai_kontrak' => 'Rp 300.000.000',
                'uang_muka'     => 'Rp 30.000.000',
                'sisa'          => 'Rp 270.000.000',
                'status'        => 'Aktif',
                'status_class'  => 'normal',
                'keterangan'    => '-',
            ],
            [
                'no_aset'       => 'AST-TGL-002',
                'nama_penyewa'  => 'PT. Maju Bersama',
                'daop'          => 'Daop 4',
                'unit'          => 'Properti',
                'nm'            => 'KA-BD-02',
                'mr'            => 'MR-002',
                'no_kontrak'    => 'KTR-2024-002',
                'tgl_mulai'     => '15-02-2024',
                'tgl_akhir'     => '14-02-2026',
                'nm2'           => 'NM-003',
                'luas'          => '180 m²',
                'harga_satuan'  => 'Rp 950.000',
                'nilai_kontrak' => 'Rp 171.000.000',
                'uang_muka'     => 'Rp 17.100.000',
                'sisa'          => 'Rp 153.900.000',
                'status'        => 'Aktif',
                'status_class'  => 'normal',
                'keterangan'    => '-',
            ],
            [
                'no_aset'       => 'AST-GDG-003',
                'nama_penyewa'  => 'CV. Sumber Rejeki',
                'daop'          => 'Daop 4',
                'unit'          => 'Logistik',
                'nm'            => 'KA-GD-01',
                'mr'            => 'MR-003',
                'no_kontrak'    => 'KTR-2024-003',
                'tgl_mulai'     => '01-03-2024',
                'tgl_akhir'     => '28-02-2025',
                'nm2'           => 'NM-004',
                'luas'          => '500 m²',
                'harga_satuan'  => 'Rp 800.000',
                'nilai_kontrak' => 'Rp 400.000.000',
                'uang_muka'     => 'Rp 0',
                'sisa'          => 'Rp 400.000.000',
                'status'        => 'Backlog',
                'status_class'  => 'danger',
                'keterangan'    => 'Belum dibayar',
            ],
            [
                'no_aset'       => 'AST-LHN-004',
                'nama_penyewa'  => 'H. Supriyadi, SE',
                'daop'          => 'Daop 4',
                'unit'          => 'Properti',
                'nm'            => 'KA-LH-01',
                'mr'            => 'MR-004',
                'no_kontrak'    => 'KTR-2024-004',
                'tgl_mulai'     => '01-04-2024',
                'tgl_akhir'     => '31-03-2026',
                'nm2'           => 'NM-005',
                'luas'          => '320 m²',
                'harga_satuan'  => 'Rp 1.500.000',
                'nilai_kontrak' => 'Rp 480.000.000',
                'uang_muka'     => 'Rp 48.000.000',
                'sisa'          => 'Rp 432.000.000',
                'status'        => 'Backlog',
                'status_class'  => 'danger',
                'keterangan'    => 'Cicilan tertunggak',
            ],
            [
                'no_aset'       => 'AST-KOS-005',
                'nama_penyewa'  => 'Ibu Siti Rahayu',
                'daop'          => 'Daop 4',
                'unit'          => 'Properti',
                'nm'            => 'KA-KS-01',
                'mr'            => 'MR-005',
                'no_kontrak'    => 'KTR-2024-005',
                'tgl_mulai'     => '01-05-2024',
                'tgl_akhir'     => '30-04-2025',
                'nm2'           => 'NM-006',
                'luas'          => '90 m²',
                'harga_satuan'  => 'Rp 600.000',
                'nilai_kontrak' => 'Rp 54.000.000',
                'uang_muka'     => 'Rp 5.400.000',
                'sisa'          => 'Rp 48.600.000',
                'status'        => 'Peringatan',
                'status_class'  => 'warning',
                'keterangan'    => 'Segera diurus',
            ],
            [
                'no_aset'       => 'AST-TGL-006',
                'nama_penyewa'  => 'PT. Nusantara Indah',
                'daop'          => 'Daop 4',
                'unit'          => 'Properti',
                'nm'            => 'KA-BD-03',
                'mr'            => 'MR-006',
                'no_kontrak'    => 'KTR-2024-006',
                'tgl_mulai'     => '01-06-2024',
                'tgl_akhir'     => '31-05-2026',
                'nm2'           => 'NM-007',
                'luas'          => '410 m²',
                'harga_satuan'  => 'Rp 1.100.000',
                'nilai_kontrak' => 'Rp 451.000.000',
                'uang_muka'     => 'Rp 45.100.000',
                'sisa'          => 'Rp 405.900.000',
                'status'        => 'Aktif',
                'status_class'  => 'normal',
                'keterangan'    => '-',
            ],
            [
                'no_aset'       => 'AST-GDG-007',
                'nama_penyewa'  => 'UD. Karya Mandiri',
                'daop'          => 'Daop 4',
                'unit'          => 'Logistik',
                'nm'            => 'KA-GD-02',
                'mr'            => 'MR-007',
                'no_kontrak'    => 'KTR-2024-007',
                'tgl_mulai'     => '10-07-2024',
                'tgl_akhir'     => '09-07-2025',
                'nm2'           => 'NM-008',
                'luas'          => '220 m²',
                'harga_satuan'  => 'Rp 750.000',
                'nilai_kontrak' => 'Rp 165.000.000',
                'uang_muka'     => 'Rp 0',
                'sisa'          => 'Rp 165.000.000',
                'status'        => 'Backlog',
                'status_class'  => 'danger',
                'keterangan'    => 'Tidak ada pembayaran',
            ],
            [
                'no_aset'       => 'AST-LHN-008',
                'nama_penyewa'  => 'Bapak Agus Santoso',
                'daop'          => 'Daop 4',
                'unit'          => 'Properti',
                'nm'            => 'KA-LH-02',
                'mr'            => 'MR-008',
                'no_kontrak'    => 'KTR-2024-008',
                'tgl_mulai'     => '15-08-2024',
                'tgl_akhir'     => '14-08-2026',
                'nm2'           => 'NM-009',
                'luas'          => '280 m²',
                'harga_satuan'  => 'Rp 900.000',
                'nilai_kontrak' => 'Rp 252.000.000',
                'uang_muka'     => 'Rp 25.200.000',
                'sisa'          => 'Rp 226.800.000',
                'status'        => 'Aktif',
                'status_class'  => 'normal',
                'keterangan'    => '-',
            ],
            [
                'no_aset'       => 'AST-TGL-009',
                'nama_penyewa'  => 'PT. Bangun Jaya',
                'daop'          => 'Daop 4',
                'unit'          => 'Properti',
                'nm'            => 'KA-BD-04',
                'mr'            => 'MR-009',
                'no_kontrak'    => 'KTR-2024-009',
                'tgl_mulai'     => '01-09-2024',
                'tgl_akhir'     => '31-08-2025',
                'nm2'           => 'NM-010',
                'luas'          => '150 m²',
                'harga_satuan'  => 'Rp 1.300.000',
                'nilai_kontrak' => 'Rp 195.000.000',
                'uang_muka'     => 'Rp 0',
                'sisa'          => 'Rp 195.000.000',
                'status'        => 'Peringatan',
                'status_class'  => 'warning',
                'keterangan'    => 'Belum lunas',
            ],
            [
                'no_aset'       => 'AST-GDG-010',
                'nama_penyewa'  => 'CV. Pratama Utama',
                'daop'          => 'Daop 4',
                'unit'          => 'Logistik',
                'nm'            => 'KA-GD-03',
                'mr'            => 'MR-010',
                'no_kontrak'    => 'KTR-2024-010',
                'tgl_mulai'     => '01-10-2024',
                'tgl_akhir'     => '30-09-2026',
                'nm2'           => 'NM-011',
                'luas'          => '600 m²',
                'harga_satuan'  => 'Rp 700.000',
                'nilai_kontrak' => 'Rp 420.000.000',
                'uang_muka'     => 'Rp 42.000.000',
                'sisa'          => 'Rp 378.000.000',
                'status'        => 'Aktif',
                'status_class'  => 'normal',
                'keterangan'    => '-',
            ],
        ];

        return view('backlog', compact('items'));
    }
}

